### ISSUE TITLE
Please create Git tags for releases

### ISSUE THREAD

**Issue by robbat2** [danfoster/puppet-sysfs#1]
Please create Git tags that match your PuppetForge releases.

**Comment by LinguineCode** [comment]
+1, easy to do and gets your module more respect

**Comment by danfoster** [comment]
I had forgot about this, sorry. Thanks for the bump.

Tagged the existing `v0.1.1` release: https://github.com/danfoster/puppet-sysfs/releases/tag/v0.1.1

I've also tagged and released `v0.2.0`
